frontend.enableClientVersionCheck:
- value: true
  constraints: {}
frontend.keepAliveMaxConnectionAge:
- value: 87600h # 10 years
frontend.keepAliveTime:
- value: 87600h # 10 years
frontend.enablePersistencePriorityRateLimiting:
- value: 200000
frontend.persistenceGlobalMaxQPS:
- value: 300000
  constraints: {}
frontend.throttledLogRPS:
- value: 230
  constraints: {}
frontend.globalNamespaceRPS:
- value: 912000
history.persistenceGlobalMaxQPS:
- value: 30000
  constraints: {}
history.defaultActivityRetryPolicy:
- value:
    InitialIntervalInSeconds: 1
    MaximumIntervalCoefficient: 100.0
    BackoffCoefficient: 2.0
    MaximumAttempts: 0
history.defaultWorkflowRetryPolicy:
- value:
    InitialIntervalInSeconds: 1
    MaximumIntervalCoefficient: 100.0
    BackoffCoefficient: 2.0
    MaximumAttempts: 0
